export const langOptions = [
    "🟨 JavaScript",
    "🔷 TypeScript",
    "🐍 Python",
    "⚡ C++",
    // "⚙️ C",
    // "🟣 C#",
    "☕ Java",
    // "🐹 Go",
    // "🦀 Rust",
    // "🐘 PHP",
    // "🍎 Swift",
    // "🤖 Kotlin",
    // "🎯 Dart",
    // "💎 Ruby",
    // "🌙 Lua",
    // "🖥️ Shell / Bash",
    // "💙 PowerShell",
    // "📊 R",
    // "🔴 Scala",
    // "🎩 Haskell",
    // "📈 Julia",
    // "🔋 Elixir",
    // "🧪 Erlang",
    // "🐪 OCaml",
    // "🧠 Lisp",
    // "📜 Clojure",
    // "🏛️ Fortran",
    // "🌐 HTML",
    // "🎨 CSS",
    // "💅 SASS / SCSS",
    // "🗄️ SQL",
    // "◈ GraphQL",
    // "📦 JSON",
    // "📄 YAML",
    // "📰 XML",
    // "🪵 Markdown",
    // "🐝 Zig",
    // "🐚 Fish",
    // "🎻 V (Vlang)",
    // "💎 Crystal",
    // "👑 Nim",
    // "🥤 CoffeeScript",
    // "🎙️ Assembly (NASM)",
    // "❓ Not Listed",
];

export const langsColors: Record<string, string> = {
    "JavaScript":       "btm-snippet-card-left--lang--yellow",
    "TypeScript":       "btm-snippet-card-left--lang--blue",
    "Python":           "btm-snippet-card-left--lang--purple",
    "C++":              "btm-snippet-card-left--lang--red",
    "C":                "btm-snippet-card-left--lang--red",
    "C#":               "btm-snippet-card-left--lang--purple",
    "Java":             "btm-snippet-card-left--lang--orange",
    "Go":               "btm-snippet-card-left--lang--sky-blue",
    "Rust":             "btm-snippet-card-left--lang--orange",
    "PHP":              "btm-snippet-card-left--lang--purple",
    "Swift":            "btm-snippet-card-left--lang--orange",
    "Kotlin":           "btm-snippet-card-left--lang--orange",
    "Dart":             "btm-snippet-card-left--lang--sky-blue",
    "Ruby":             "btm-snippet-card-left--lang--red",
    "Lua":              "btm-snippet-card-left--lang--blue",
    "Shell / Bash":     "btm-snippet-card-left--lang--yellow",
    "PowerShell":       "btm-snippet-card-left--lang--blue",
    "R":                "btm-snippet-card-left--lang--sky-blue",
    "Scala":            "btm-snippet-card-left--lang--red",
    " Haskell":         "btm-snippet-card-left--lang--purple",
    "Julia":            "btm-snippet-card-left--lang--purple",
    "Elixir":           "btm-snippet-card-left--lang--purple",
    "Erlang":           "btm-snippet-card-left--lang--red",
    "OCaml":            "btm-snippet-card-left--lang--orange",
    "Lisp":             "btm-snippet-card-left--lang--yellow",
    "Clojure":          "btm-snippet-card-left--lang--sky-blue",
    "Fortran":          "btm-snippet-card-left--lang--blue",
    "HTML":             "btm-snippet-card-left--lang--orange",
    "CSS":              "btm-snippet-card-left--lang--pink",
    "SASS / SCSS":      "btm-snippet-card-left--lang--pink",
    "SQL":              "btm-snippet-card-left--lang--sky-blue",
    "GraphQL":          "btm-snippet-card-left--lang--pink",
    "JSON":             "btm-snippet-card-left--lang--yellow",
    "YAML":             "btm-snippet-card-left--lang--red",
    "XML":              "btm-snippet-card-left--lang--orange",
    "Markdown":         "btm-snippet-card-left--lang--blue",
    "Zig":              "btm-snippet-card-left--lang--orange",
    "Fish":             "btm-snippet-card-left--lang--sky-blue",
    "V (Vlang)":        "btm-snippet-card-left--lang--blue",
    "Crystal":          "btm-snippet-card-left--lang--red",
    "Nim":              "btm-snippet-card-left--lang--yellow",
    "CoffeeScript":     "btm-snippet-card-left--lang--yellow",
    "Assembly (NASM)":  "btm-snippet-card-left--lang--red",
    "Not Listed":       "btm-snippet-card-left--lang--default",
};