export const langOptions = [
    "🟨 JavaScript",
    "🔷 TypeScript",
    "🐍 Python",
    "⚡ C++",
    "⚙️ C",
    "🟣 C#",
    "☕ Java",
    "🐹 Go",
    "🦀 Rust",
    "🐘 PHP",
    "🍎 Swift",
    "🤖 Kotlin",
    "🎯 Dart",
    "💎 Ruby",
    "🌙 Lua",
    "🖥️ Shell / Bash",
    "💙 PowerShell",
    "📊 R",
    "🔴 Scala",
    "λ Haskell",
    "📈 Julia",
    "🔋 Elixir",
    "🧪 Erlang",
    "🦄 OCaml",
    "🧠 Lisp",
    "📜 Clojure",
    "🇦 Fortran",
    "🌐 HTML",
    "🎨 CSS",
    "💅 SASS / SCSS",
    "🗄️ SQL",
    "◈ GraphQL",
    "📦 JSON",
    "📄 YAML",
    "📰 XML",
    "🪵 Markdown",
    "🐝 Zig",
    "🐚 Fish",
    "🎻 V (Vlang)",
    "💎 Crystal",
    " Nim",
    "🥤 CoffeeScript",
    "🎙️ Assembly (NASM)",
    "❓ Not Listed",
];

export const langsColors: Record<string, string> = {
    Python: "btm-snippet-card-left--lang--purple",
    "C#": "btm-snippet-card-left--lang--purple",
    Javascript: "btm-snippet-card-left--lang--yellow",
    Typescript: "btm-snippet-card-left--lang--blue",
    SQL: "btm-snippet-card-left--lang--sky-blue",
    Java: "btm-snippet-card-left--lang--orange",
    "C++": "btm-snippet-card-left--lang--red",
    CSS: "btm-snippet-card-left--lang--pink",
    SASS: "btm-snippet-card-left--lang--pink",
};